version: '3.0'
services:
  db:
    container_name: ecommerce-mysql
    image: mysql:latest
    restart: on-failure:5
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root